import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { bookings } from "@/lib/schema";
import { eq } from "drizzle-orm";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://hyderabadflowerdecorators.netlify.app";

// Serve an HTML photo page for a booking — shows all images with download links
export async function GET(
  request: Request,
  { params }: { params: Promise<{ ticket_id: string }> }
) {
  try {
    const { ticket_id } = await params;

    const result = await getDb().select().from(bookings).where(eq(bookings.ticketId, ticket_id)).limit(1);
    if (result.length === 0) {
      return new NextResponse("<h1>Booking not found</h1>", { status: 404, headers: { "Content-Type": "text/html" } });
    }

    const booking = result[0];
    const images = (booking.images as string[]) || [];
    const imageCount = images.length;

    // Build image URLs that serve from our API
    const imageUrls = images.map((_, i) => `${SITE_URL}/api/booking/image/${ticket_id}/${i}`);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HFD Booking ${ticket_id} — Reference Images</title>
<style>
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:system-ui,-apple-system,sans-serif;max-width:900px;margin:0 auto;padding:24px;background:#FAF8F5;color:#1A1A1A;}
h1{font-size:24px;color:#1A1A1A;margin-bottom:4px;}
h2{font-size:18px;color:#B8935F;margin-bottom:24px;}
.info{background:#fff;border-radius:16px;padding:20px;margin-bottom:24px;box-shadow:0 2px 12px rgba(0,0,0,0.06);}
.info table{width:100%;font-size:14px;}
.info td{padding:8px 0;}
.info .label{color:#6B6560;width:120px;}
.info .val{color:#1A1A1A;font-weight:500;}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px;margin-bottom:24px;}
.card{background:#fff;border-radius:16px;padding:16px;box-shadow:0 2px 12px rgba(0,0,0,0.06);}
.card img{width:100%;border-radius:12px;display:block;}
.card .num{text-align:center;font-size:13px;color:#6B6560;margin-top:8px;}
.btn{display:inline-block;background:#B8935F;color:#1A1A1A;padding:14px 28px;border-radius:30px;text-decoration:none;font-weight:700;font-size:14px;margin:4px;}
.download-all{text-align:center;margin:24px 0;}
footer{font-size:11px;color:#6B6560;text-align:center;margin-top:32px;}
</style>
</head>
<body>
<h1>🌸 Hyderabad Flower Decorators</h1>
<h2>Booking ${ticket_id} — Reference Images</h2>

<div class="info">
<table>
<tr><td class="label">Customer</td><td class="val">${booking.fullName}</td></tr>
<tr><td class="label">Phone</td><td class="val"><a href="tel:${booking.phone}" style="color:#B8935F">${booking.phone}</a></td></tr>
<tr><td class="label">Event</td><td class="val">${booking.eventType.replace(/-/g, " ")}</td></tr>
<tr><td class="label">Date</td><td class="val">${booking.eventDate}</td></tr>
<tr><td class="label">Time</td><td class="val">${booking.preferredTime}</td></tr>
<tr><td class="label">Venue</td><td class="val">${booking.venueAddress}</td></tr>
</table>
</div>

<p style="margin-bottom:16px;font-size:15px;">${imageCount} reference image(s):</p>

<div class="grid">
${imageUrls.map((url, i) => `
<div class="card">
<a href="${url}" target="_blank"><img src="${url}" alt="Image ${i + 1}"></a>
<p class="num">Image ${i + 1} — <a href="${url}" target="_blank" download style="color:#B8935F">Download</a></p>
</div>
`).join("\n")}
</div>

<div class="download-all">
${imageUrls.map((url, i) => `<a href="${url}" target="_blank" download class="btn">Image ${i + 1}</a>`).join("\n")}
</div>

<footer>Generated by HFD Admin &bull; ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</footer>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "public, max-age=3600",
      },
    });
  } catch {
    return new NextResponse("<h1>Error loading photos</h1>", { status: 500, headers: { "Content-Type": "text/html" } });
  }
}
